### ISSUE TITLE
server.stop() doesn't close request log filehandle

### ISSUE THREAD

**Issue by tripodsan** [adobe/git-server#153] opened 2020-01-16 03:19 UTC
trying to delete the `logs` directory after `server.stop()` hangs on windows, probably because the filehandle to `logs/request.log` is not closed.

**Comment by stefan-guggisberg** [comment] 2020-02-19 01:49
I am able to reproduce the problem on windows. The `error.log` (`helix-log` `FileLogger` instance) and the `request.log` (`morgan`) cannot be deleted (`EPERM` error). While the respective file handles could be closed on `server.stop()` there will be problems when `server.start()` is called again since since both `FileLogger` and the `morgan` middleware have a different life cycle.

`server.destroy()` (or similar) would probably a better place for releasing file handles.

**Comment by stefan-guggisberg** [comment] 2021-09-23 15:18
won't fix

**Closed by stefan-guggisberg** 2021-09-23 15:18 UTC
